### ISSUE TITLE
make_manifest aws container not working

### ISSUE THREAD

**Issue by rvadisala** [cloudfoundry-community/postgresql-docker-boshrelease#15]
root@ip-10-0-0-9:~/postgresql-docker-boshrelease/templates# ./make_manifest aws container embedded
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Acting as user 'admin' on 'my-bosh'
my-bosh aws_cpi 99e40f7e-2859-4fb3-9374-93969adda76d bosh-aws-xen-hvm-ubuntu-trusty-go_agent
2 error(s) detected:
- $.meta.subnets: inappropriate use of (( merge )) operator outside of a list (this is spruce, after all)
- $.networks.0.subnets: inappropriate use of (( merge )) operator outside of a list (this is spruce, after all)

root@ip-10-0-0-9:~/postgresql-docker-boshrelease/templates#

**Comment by drnic** [comment]
TODO: assume a cloud-config director in future https://github.com/cloudfoundry-community/postgresql-docker-boshrelease/issues/27
