### ISSUE TITLE
Is it possible to configure instance size quota?

### ISSUE THREAD

**Issue by yatzek-zz** [cloudfoundry-community/postgresql-docker-boshrelease#16]

**Comment by drnic** [comment]
You can set the size of RAM for docker containers in each plan (and then could have diff plans mapping to ram quotas)

See https://github.com/cloudfoundry-community/docker-boshrelease/blob/master/examples/docker-broker-aws.yml under memcached service for "memory: 128M" example

**Comment by yatzek-zz** [comment]
What about disk size? Is there a simple way to restrict individual db size?

**Comment by drnic** [comment]
I don't believe docker nor cf-containers-broker offers a volume size constraint.

Perhaps something could be configured into PG itself. Do you know anything?

**Comment by yatzek-zz** [comment]
Unfortunately not, quick google search does not return anything straightforward.
