### ISSUE TITLE
Can't generate a manifest for openstack

### ISSUE THREAD

**Issue by tvelykyy** [cloudfoundry-community/postgresql-docker-boshrelease#26]
./templates/make_manifest openstack broker embedded

2 error(s) detected:
 - $.meta.subnets: inappropriate use of (( merge )) operator outside of a list (this is spruce, after all)
 - $.networks.0.subnets: inappropriate use of (( merge )) operator outside of a list (this is spruce, after all)

**Comment by drnic** [comment]
TODO: assume a cloud-config director in future https://github.com/cloudfoundry-community/postgresql-docker-boshrelease/issues/27
