### ISSUE TITLE
How to install a Postgres extension at database creation

### ISSUE THREAD

**Issue by samdai** [cloudfoundry-community/postgresql-docker-boshrelease#8]
I want to install a Postgres extension "ltree" at database creation, but don't know how to configure it. In file /images/postgresql93/scripts/first_run.sh, if we can pass value to system environment variable "POSTGRES_EXTENSIONS", can install extensions at database creation, but don't know how to pass value to it.

**Comment by drnic** [comment]
I haven't tried setting up extensions yet, but you should be able to setup env vars by pass thru of parameters at "cf create-service" time.

Perhaps try:

cf cs postgresql93 free test -c '{"POSTGRES_EXTENSIONS": "xyz"}'

**Comment by samdai** [comment]
Thanks, it works.

**Comment by drnic** [comment]
If you write any blog posts etc about getting it working let me know and I'll add to the readme and/or PR the readme yourself.

Thanks for getting it working!
