### ISSUE TITLE
How to persist database data?

### ISSUE THREAD

**Issue by samdai** [cloudfoundry-community/postgresql-docker-boshrelease#9]
Currently when I use postgresql-docker-boshrelease to create postgresql service, the PostgreSQL server is configured to store data in the `/data` directory inside the container. how can I map the container's `/data` volume to a volume on the host so the data becomes independent of the running container?

**Comment by drnic** [comment]
That is already performed by cf-containers-broker. Have a look in /var/vcap/store

**Comment by samdai** [comment]
got it, thanks.
